FROM node:23-bookworm

ARG USER_ID
ARG GROUP_ID


# RUN apt-get update && apt-get install -y openssh-server 
# RUN sed -i 's/.*PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
# RUN sed -i 's/.*PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
# RUN echo "root:dev" | chpasswd

RUN npm install -g create-react-app

USER node

WORKDIR /app/
